# Generated by Django 4.2.7 on 2023-12-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='photo_auther',
            new_name='photo_author',
        ),
    ]
